### ISSUE TITLE
Scripts for accuracy and time comparisons

### ISSUE THREAD

**Issue by jedbrown** [zongyi-li/fourier_neural_operator#1]
It would be useful if you could set up infrastructure so that one could run a modified solver configuration (both for the conventional "data generation" solvers and the FNO) and immediately get accuracy feedback. Maybe you have this and could just document what you ran for https://twitter.com/ZongyiLiCaltech/status/1319137209061011456, or streamline that process.

**Comment by zongyi-li** [comment]
Sorry for the delayed reply. 
To train from scratch, download the data and run _fourier_3d.py_
To evaluate pre-train model, download the model and run _scripts/eval.py_
For the super-resolution (visualized in Twitter), run _scripts/super_resolution.py_
The conventional solver is also given in _data_generation/ns_2d.py_.
And sorry for the coding style. Thanks!
