### ISSUE TITLE
Configuration value in fourier_1D.py

### ISSUE THREAD

**Issue by SairamPrabhakar** [zongyi-li/fourier_neural_operator#11]
Hi,

It seems that for the burgers_data_R10.mat dataset dimensions, the value of h on line 132 must be 2^13 rather than 2^10? 

Thanks,
Sairam

**Comment by zongyi-li** [comment]
Hi Sairam,

Yes, you are right! The original code is for the 2^10 data. Please use 2^13 instead.

Thanks,
Zongyi
