### ISSUE TITLE
reporting something odd:

### ISSUE THREAD

**Issue by szat** [zongyi-li/fourier_neural_operator#13]
Hi!

In the 2d case, the training set is 241x241, but in fourier_2d.py you have

```
r = 5
h = int(((421 - 1)/r) + 1)
s = h
```

```
reader = MatReader(TRAIN_PATH)
x_train = reader.read_field('coeff')[:ntrain,::r,::r][:,:s,:s]

```
Did you not mean h = int(((241-1)/r) + 1?
Also 
```
x_train = reader.read_field('coeff')[:ntrain,::r,::r][:,:s,:s]
== 
x_train = reader.read_field('coeff')[:ntrain,::r,::r]
```
since s > x_train.shape[1]

Maybe I am misunderstanding something. 
Sincerely,
Adrian

**Comment by zongyi-li** [comment]
Hi Adrian, 
You are right, for the 241x241 data, please use h = int(((241 - 1)/r) + 1).
The original code is for 421x421 data.

Thanks!
Zongyi
