### ISSUE TITLE
ns_data_V10000_N1200_T20.mat

### ISSUE THREAD

**Issue by dbl001** [zongyi-li/fourier_neural_operator#15]
fourier_2d_rnn.py references 'ns_data_V10000_N1200_T20.mat':
E.g.
TRAIN_PATH = '/data/fourier_neural_operator/ns_data_V10000_N1200_T20.mat'
TEST_PATH =  '/data/fourier_neural/operator/ns_data_V10000_N1200_T20.mat'

The repository state: 
"We provide the Burgers equation and Darcy flow datasets we used in the paper."

Is the Navier-Stoke file: ns_data_V10000_N1200_T20.mat available?

**Comment by zongyi-li** [comment]
Yes, I just uploaded this file _NavierStokes_V1e-5_N1200_T20.mat_ on https://drive.google.com/drive/folders/1UnbQh2WWc6knEHbLn-ZaXrKUZhp7pjt-?usp=sharing
It's the Navier-Stokes data with viscosity=1e-5 (not 10000), 1200 samples, 20 time steps. Notice viscosity=1e-5 is significantly harder than viscosity=1e-4, we expect ~20% error, as reported in the paper.
