### ISSUE TITLE
last layer in 3d example

### ISSUE THREAD

**Issue by GeorgeLiang3** [zongyi-li/fourier_neural_operator#16]
Hi Zongyi, 

Really nice work, maybe a stupid question, why we have `x = self.bn3(x1)`for the last layer in the 3d example but `x = self.bn3(x1 + x2)` for 1d and 2d? 

Thanks
George

**Comment by zongyi-li** [comment]
Thanks for the catch! It's a silly typo... I will fix it immediately.

Thanks,
Zongyi
