### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by persistz** [zongyi-li/fourier_neural_operator#18]
A lot of Pytorch issues occurred during my reproducing of the repo.
Could you provide the Pytorch version you used? 
I think it will help a lot, thanks!

BTW, very detailed code was provided, but it would be better if more comments and more detailed 'readme' files are available.

**Comment by zongyi-li** [comment]
We are using Pytorch 1.6.0. 
And sorry for the lack of comments... We will try to clean it up. Meanwhile, feel free to post any questions. Thanks!

**Comment by persistz** [comment]
Thanks for your prompt reply.
Closed.
