### ISSUE TITLE
there are some wrong in next code.

### ISSUE THREAD

**Issue by luyifanlu** [zongyi-li/fourier_neural_operator#2]
the arugment is different
https://github.com/zongyi-li/fourier_neural_operator/blob/614d9132f8995a34424d39dc2272afae0e933b24/scripts/fourier_on_images.py#L140
`class SpectralConv2d(nn.Module):`
`  def __init__(self, in_channels, out_channels, modes1, modes2):`

**Comment by zongyi-li** [comment]
Oops, this piece of code is outdated. Will update it.
Thanks for the catch!

**Comment by luyifanlu** [comment]
I don“t know if you have tested  the code that the arugment is also different.  
even if i correct the arugment with same , it will report a error that size of dimension does not match previous size
https://github.com/zongyi-li/fourier_neural_operator/blob/90bbd4c9ffa84b91ec2daa86660148861989adec/scripts/fourier_on_images.py#L34
https://github.com/zongyi-li/fourier_neural_operator/blob/90bbd4c9ffa84b91ec2daa86660148861989adec/scripts/fourier_on_images.py#L116
