### ISSUE TITLE
RunTimeError when executing fourier_1D.py

### ISSUE THREAD

**Issue by juliandwain** [zongyi-li/fourier_neural_operator#21]
Hi,

I tried executing your 1D example. I downloaded the corresponding data from the Google Drive folder you provided in the readme and copy-pasted the file into my env, and I get the following error:

````bash
Traceback (most recent call last):
  File "fourier_1D.py", line 196, in <module>
    x_train = torch.cat([x_train.reshape(ntrain, s, 1),
RuntimeError: shape '[1000, 1024, 1]' is invalid for input of size 8192000
````

This error is caused by the following code block:

````python
# cat the locations information
grid = np.linspace(0, 2*np.pi, s).reshape(1, s, 1)
grid = torch.tensor(grid, dtype=torch.float)
x_train = torch.cat([x_train.reshape(ntrain, s, 1),
                     grid.repeat(ntrain, 1, 1)], dim=2)
x_test = torch.cat([x_test.reshape(ntest, s, 1),
                    grid.repeat(ntest, 1, 1)], dim=2)
````

The error seems to occur when constructing `x_train`.

My env configuration looks like the following:
- python: version 3.8.5
- pytorch: version 1.7.0
- numpy: version 1.19.2

I changed nothing within the file, I created a corresponding `data` folder which contains `burgers_data_R10.mat` so that I didn't even have to change that line.

**Comment by zongyi-li** [comment]
There are two Burgers dataset with different resolutions. Please use
```
sub = 2**3 #subsampling rate
h = 2**13 // sub
s = h
```
Also see #6
