### ISSUE TITLE
x_train shape error in fourier_1d.py

### ISSUE THREAD

**Issue by xiaoyuxie-vico** [zongyi-li/fourier_neural_operator#22]
I tried to use the dataset called "Burgers_R10.zip" in your google drive shared files. But when I ran your "fourier_1d.py" code, it showed error information like the below: 

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-21-e4813e02a626> in <module>()
    186 grid = np.linspace(0, 2*np.pi, s).reshape(1, s, 1)
    187 grid = torch.tensor(grid, dtype=torch.float)
--> 188 x_train = torch.cat([x_train.reshape(ntrain,s,1), grid.repeat(ntrain,1,1)], dim=2)
    189 x_test = torch.cat([x_test.reshape(ntest,s,1), grid.repeat(ntest,1,1)], dim=2)
    190 

RuntimeError: shape '[1000, 1024, 1]' is invalid for input of size 8192000
```
It seems the shape of the x_train is [1000, 8192], but in line 188 the x_train needs to be [1000, 1024].

So, I wonder if the dataset is correct for this code? And could you describe the rows and columns of the dataset? It is really confusing now.

**Comment by zongyi-li** [comment]
There are two Burgers datasets with different resolutions. Please use

```
sub = 2**3 #subsampling rate
h = 2**13 // sub
s = h
```

Each row of the dataset is a sample (a realization with a different initialization). The second index is the discretization. So the [1000, 8192] data is of 1000 training samples with a 8192 discretization of the domain.

Also see #6

**Comment by xiaoyuxie-vico** [comment]
Thanks for your reply! The problem is solved.
