### ISSUE TITLE
Why permute the data in Fourier_1d.py

### ISSUE THREAD

**Issue by xiaoyuxie-vico** [zongyi-li/fourier_neural_operator#23]
For line 104 (` x = x.permute(0, 2, 1)`) in Fourier_1d.py, you change the axis using permute. But I am not clear why do you do that? Is this for some special reasons?

**Comment by zongyi-li** [comment]
In our implementation, the input tensor is (batch, x, channel). We apply a Linear layer to the channel space, permute it to (batch, channel, x), and then apply convolution layers. 

I think the permute operation can be avoided if you directly input tensor as (batch, channel, x) and use 1X1 conv as the Linear layer.

**Comment by xiaoyuxie-vico** [comment]
Thanks for your explanation! I understood.
