### ISSUE TITLE
How dataset for Burgers equation created?

### ISSUE THREAD

**Issue by xiaoyuxie-vico** [zongyi-li/fourier_neural_operator#24]
In your paper called "Fourier Neural Operator for Parametric Partial Differential Equations", you described how you created the Burgers equation dataset on Page 15, like below:
"The initial condition u_0(x) is generated according to u_0 ~ µ where µ = N(0, 625((-\delta+25I) ^{-2} ) with periodic boundary conditions." 

I am not very clear about the initial condition and boundary condition. Could you describe the meaning of \delta and I in u_0 and describe what are the periodic boundary conditions? Thanks for your help!

**Comment by zongyi-li** [comment]
The initial conditions are sampled from a gaussian random field where 625((-\delta+25I) ^{-2} is the variance. Basically we are sampling continuous functions following a gaussian distribution, where the variance describes the "size" of these bumps. Larger variance for steeper functions. You can see an example of our implementation [random_fields.py](https://github.com/zongyi-li/fourier_neural_operator/blob/master/data_generation/random_fields.py). The boundary is periodic.

**Comment by xiaoyuxie-vico** [comment]
Thanks for your explanation!
