### ISSUE TITLE
About the spatial domain D

### ISSUE THREAD

**Issue by Kakitan-saikou** [zongyi-li/fourier_neural_operator#25]
In your paper, you defined the spatial domain D as a bounded, open set.
And I noticed that the spatial domain D in your experiments are always (0,1) or (0,1)^2; but I think this 'fourier neural opertor' method is still practical no matter what the shape of the spatial domain D is(for example, D is a circle or a domain with some irregular shapes). 
Could you please tell me if I am right or not?  Thank you very much!

**Comment by zongyi-li** [comment]
Yes, it is possible to apply the Fourier neural operator to different domains.
-  Ideally, this problem should have an efficient fourier representation (for example it's a good sign if people can use pseudo-spectrum methods to solve it).
- The current implementation is based on FFT, which is the best on a uniform grid. To work on a different grid you may need to use a different fourier transform.

Thanks!

**Comment by Kakitan-saikou** [comment]
Oh I see. Thank you!
