### ISSUE TITLE
Explanation about the .mat data files

### ISSUE THREAD

**Issue by rafsanabir** [zongyi-li/fourier_neural_operator#27]
Hi, I was looking at the data files you have uploaded to google drive. Could you please provide a brief explanation of what the data files hold? For example, burgers_data_R10.mat has 5 different arrays of (2048, 8192) size. I understand 'u' to be the solution, but what are 'a', 'a_smooth', 'a_smooth_x' and 'a_x'?

**Comment by zongyi-li** [comment]
Hi, 'u' is the solution; 'a' is the parameter. The rest of them are some feature engineering we used in the previous paper. 'a_smooth' is the gaussian smoothing verison of 'a'. 'a_smooth_x' and 'a_smooth_y' are the derivative of 'a_smooth' w.r.t. x and y. We didn't use these features in our Fourier neural operator. Thanks

**Comment by rafsanabir** [comment]
Thank you! That was very helpful. If you don't mind me asking, do you have plans of uploading the codes that you used for solving Burgers and Darcy flow, as you have very helpfully provided for the NS here? 
Thanks again!

**Comment by zongyi-li** [comment]
Sure I have just uploaded the data generation scripts for Burgers and Darcy (https://github.com/zongyi-li/fourier_neural_operator/tree/master/data_generation). They are written in matlab. Hope it helps!

**Comment by rafsanabir** [comment]
Thank you so much! I really appreciate it!

**Comment by baogumimimi** [comment]
> Sure I have just uploaded the data generation scripts for Burgers and Darcy (https://github.com/zongyi-li/fourier_neural_operator/tree/master/data_generation). They are written in matlab. Hope it helps!

**Comment by baogumimimi** [comment]
> Sure I have just uploaded the data generation scripts for Burgers and Darcy (https://github.com/zongyi-li/fourier_neural_operator/tree/master/data_generation). They are written in matlab. Hope it helps!

hi,This link won't open.Could you please upload a new one

**Comment by zongyi-li** [comment]
Hi! here is a copy https://github.com/li-Pingan/fourier-neural-operator/tree/main/data_generation

**Comment by baogumimimi** [comment]
Thank you so much!!
