### ISSUE TITLE
Data generation code for Burgers

### ISSUE THREAD

**Issue by rafsanabir** [zongyi-li/fourier_neural_operator#29]
Hi, I have another question about the data generation code for the Burgers equation. As far as I understood, in the code that you have provided here, the GRF function yields the initial condition values (1024 values at 1024 grid points) at one specific time-step. Using these initial values, the Burgers is solved at 201 time-steps and the solutions are stored in the 'Output' variable (1x201x1024 final size). Assuming my understanding is correct, I am having difficulty wrapping my head around the fields 'a' and 'u' in the 'burgers_data_R10.mat' file. If both have the same shape (2048x8192), 

1. If 'a' is the initial conditions 'u_0', how did you generate 2048 instances of it? 

2. Are these all separate initial conditions, which will all produce separate solutions 'u' for each of the instances? Or is 'a' built from the solution of Burgers at each time-step? Which I doubt because you don't really use the last time-step as your train data for y, y_train has the shape 1000x1024.

I guess I am just really confused. Could you please help me out here? Thanks!

**Comment by zongyi-li** [comment]
Sorry for the slow response. In the data generation code, we have

```
N = 1;
s = 1024;
steps = 200;
```
To get the data as burgers_data_R10.mat, you can set N=2048 and s=8192. The first time step is set as `a` and the last time step is set as 'u'. For your question, yes they are different initial conditions.

**Comment by Sunny-DV** [comment]
Hi, I have some question 
1. To generate the initial value you used the normal distribution with mean 0 but i did not understand the ∆, I term.
2. I want to use this method to solve diffusion equation and in last want to predict the result using time and x as input and then try to make it for x, y and x,y,z. If i am right i should use the fourier 2D with time model. I am bit confused. Could you please help me?

**Comment by zongyi-li** [comment]
1. The distribution is a Gaussian random field where the variance indicates how curved the function is. It's equivalent to sample the coefficient in the Fourier domain and scales the coefficient of the variance. You can see our sample code in the data generation folder [andom_fields.py](https://github.com/zongyi-li/fourier_neural_operator/blob/master/data_generation/navier_stokes/random_fields.py) 
2. Yes you can start with fourier 2D. Feel free to let me know if you get any problems.
