### ISSUE TITLE
Getting the reported metrics in Table 3

### ISSUE THREAD

**Issue by alasdairtran** [zongyi-li/fourier_neural_operator#34]
Hi Zongyi,

In the file `lowrank_2d_time.py`, you print out [here](https://github.com/zongyi-li/fourier_neural_operator/blob/73854fa9bcf75229f2871e0d38b80ac30586859a/lowrank_2d_time.py#L283) two metrics on the test data: `test_l2_step` and `test_l2_full`. Just wondering, which one of these two did you use to report the numbers in Table 3 (Benchmarks on Navier Stokes) of your paper?

**Comment by zongyi-li** [comment]
I believe we used `test_l2_full`.
