### ISSUE TITLE
Can this method be implemented on multiple IC PDEs?

### ISSUE THREAD

**Issue by ChironJC** [zongyi-li/fourier_neural_operator#38]
For example we have wave equation as following:
U_tt = U_xx
U(x,0) = phi(x)
U'(x,0) = psi(x)

Can I set input initial condition as (u0, u0_prime, x) and solve it?

**Comment by zongyi-li** [comment]
Yes, that's right!

**Comment by ChironJC** [comment]
> Yes, that's right!

Over fitting happens. I'll try more.
