### ISSUE TITLE
there are som wrong in code

### ISSUE THREAD

**Issue by Fish08042** [zongyi-li/fourier_neural_operator#4]
# fourier_neural_operator/fourier_1d.py

class SimpleBlock1d(nn.Module):
    ......
    def forward(self, x):

        x = self.fc0(x)
        x = x.permute(0, 2, 1)

        x1 = self.conv0(x)
        x2 = self.w0(x)
        x = self.bn0(x1 + x2)
        x = F.relu(x)
        x1 = self.conv1(x)
        x2 = self.w1(x)
        x = self.bn1(x1 + x2)
        x = F.relu(x)
        x1 = self.conv2(x)
        x2 = self.w2(x)
        x = self.bn2(x1 + x2)
        x = F.relu(x)
        x = self.conv3(x)
        x2 = self.w3(x)
        x = self.bn3(x1 + x2)
......

**the third row to the last，maybe you means “ x1 = self.conv3(x)”**

**Comment by zongyi-li** [comment]
Thank you a lot for the catch! Will update it.
