### ISSUE TITLE
A few questions about fourier_2d_time.py

### ISSUE THREAD

**Issue by Oliver-ZCK** [zongyi-li/fourier_neural_operator#40]
Hello, I have a few questions about fourier_2d_time.py

There is no normalization before training, but it has de-normalization in the prediction section (line 294).
`out = y_normalizer.decode(out)`
I have tried to delete line 294 directly, but this will cause an error when calculating loss because the dimensions of “out” and “y” are inconsistent. I also tried to add normalization based on fourier_3d.py. The program runs successfully, but the prediction result is not quite correct. I think the reason is that the dimension of the “x” is (1,64,64,10), “out” is (1,64,64,1) and “out” after normalization is (1,64,64,10). The dimension of “out” is improved to (1,64,64,10) by normalization instead of iteration in time. I think the prediction process should be the same as the training process, which should be iterated over time. I changed the code in the prediction section, and the results looked correct.

**Comment by zongyi-li** [comment]
Right. The code commented out is obsolete. Please use the validation code (line 259-281) for testing.

**Comment by Oliver-ZCK** [comment]
Thank you！

**Comment by Oliver-ZCK** [comment]
I also notice that the input shape is (batchsize, x=64, y=64, c=12)(line 81), but the input shape in the training part is still (batchsize, x=64, y=64, c=10). I'm not sure what does the ’2 locations‘ mean？

**Comment by zongyi-li** [comment]
We add the grid information as part of the input. For the fourier_1d, fourier_2d, and fourier_3d, the grid is directly added during the data preparration.  For fourier_2d_time, this code is moved inside the network for simplicity, at line 139-144.

**Comment by Oliver-ZCK** [comment]
Thank you so much!
