### ISSUE TITLE
Run time error in Fourier_1d.py, line 227

### ISSUE THREAD

**Issue by atvassilev** [zongyi-li/fourier_neural_operator#42]
Hi, I tried to run your 1D example but ran into a problem - see below. The script crashes in reporting the loss. Any suggestions for how to fix it?

499 0.3591817901469767 5.364698648691046e-07 0.001563040729612112 0.0031099164858460425
Traceback (most recent call last):
  File "fourier_1d.py", line 227, in <module>
    pred[index] = out
RuntimeError: expand(torch.cuda.FloatTensor{[1024, 1]}, size=[1024]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

I am using a runtime environment with
    - cudatoolkit=10.1
    - pytorch=1.8.1

**Comment by zongyi-li** [comment]
Sorry the code in the end may have some issues. But it has finished training. As you can see, the error is `0.0031099164858460425`

To fix the evalution code, please change  `pred[index] = out` to `pred[index] = out.reshape(-1)`
Thanks!

**Comment by atvassilev** [comment]
OK, this did the trick, thanks for the quick reply!
