### ISSUE TITLE
fourier_on_images.py needs to be updated

### ISSUE THREAD

**Issue by ReGhane** [zongyi-li/fourier_neural_operator#44]
Greetings and thank you for your awesome work!

When I wanted to run fourier_on_images.py, I encountered errors in several parts of the code:

1) I believe that the `compl_mul2d(a,b)` should be updated using the codes in the fourier_2d_tuned.py as it raises an error

2) Pytorch seems to have updated the radon transform syntax, so `torch.rfft` should be changed to `torch.fft.rfftn`

I could make the code work, but I wanted to use the official release by you. Thanks again!

**Comment by zongyi-li** [comment]
Sorry the fourier_on_images.py is outdated. Yes it needs to be updated as fourier_2d.py. Unfortunately we don't have the bandwidth to work on it at this moment...  You are welcome to submit a pull request. It will be very helpful to us. Thanks!

**Comment by zongyi-li** [comment]
FNO-Transformer model for images problem https://arxiv.org/pdf/2111.13587.pdf
