### ISSUE TITLE
NSE hyperparmeters used in paper

### ISSUE THREAD

**Issue by soto-13** [zongyi-li/fourier_neural_operator#45]
Hello

In order to reproduce results, I'd like to know what hyper-parameters you used for producing the various flows using NSE.

Specifically:

For the datasets with viscosities 1e-3, 1e-4, and 1e-5

for each
fourier_2d_time.py
fourier_3d.py

From reading around I only identified modes=12, width=32 for fourier_2d_time.py, and modes=8, width=20 for fourier_3d.py for viscosity=1e-4.

I think these are the most crucial ones (I will just run enough epochs etc. for the rest). I would like to train on 10 and predict 10 next frames (what is constraining the max fourier modes?)

Thanks!

**Comment by zongyi-li** [comment]
Yes I think it is correct. Sorry for the delayed response.
For fourier_3d.py, the number of mode should be smaller than T/2, so it would be better to predict at least T>=20 frames. For a smaller number of frame, fourier_2d_time.py is better.

**Comment by soto-13** [comment]
Right the time horizon is limiting. I used modes=12, width=32 with fourier_2d_time.py for all cases (these are the hyperparams for visc_1e-4, I suppose that could work with 1e-3, 1e-5 too)
