### ISSUE TITLE
Different input domains at test time

### ISSUE THREAD

**Issue by Chutlhu** [zongyi-li/fourier_neural_operator#46]
Dear Zongyi Li,
first of all, thank you for this amazing work and the availability of this repo.

I m trying your approach as a baseline for my PhD work.
In particular, I am training your model on data defined on a 64x64 grid with $x,y \in (0,1)$.
At test time the input is $x,y \in (0.4, 0,6)$. 
And, instead of a 'zoom' in the input region, the model returns the original image with artefacts. 
On the contrary, if I just upsample the input domain, e.g. 512x512 with $x,y \in (0,1)$ the results are nice.
Do you have an explanation for this behaviour?

Thank  you very much

**Comment by zongyi-li** [comment]
Right, the FNO model does global convolution. It learns a kernel defined on (0,1). It is resolution-invariant, so it can be applied on 512x512. But this kernel may not be directly applied on a different domain like (0.4, 0,6). In other words, these Fourier basis in FNO has scale 1. But on (0.4, 0,6), the new FFT's Fourier basis has scale 0.2. To work on crops, you may try to pad it (0.4, 0,6) periodically back to (0, 1).
