### ISSUE TITLE
3D spatial domain and time

### ISSUE THREAD

**Issue by norouzzadeh** [zongyi-li/fourier_neural_operator#48]
Congratulations on your great job.
It would be appreciated if you specify what modifications are required for a 3D spatial and time PDE problem.

With best regards

**Comment by zongyi-li** [comment]
Thanks! There are two ways to formulate the problem. We can either use fourier_2d_time.py but change FNO2d to FNO3d, or use fourier_3d.py, but do 4d convolution. What is the resolution and number of time steps?

**Comment by norouzzadeh** [comment]
I'm going to use the neural operator for solving soft tissue simulations. The continuum mechanics is expressed as MΔv = dtf(x, t).
where f(x, t) is the force, x is the displacement, t is the time, and Δv is the velocity difference in Δt.
Currently the equation is solved using FEM technique by SOFA (https://www.sofa-framework.org/).
I'm not sure what resolution might be applicable and I'm going to test various resolutions.
The time step of at least 10 and up to 50 is preferred.
Thanks again for your kindly considerations.

**Comment by zongyi-li** [comment]
That certainly makes sense. And may I ask how many simulations/instances do you have? 
Honestly speaking, 3D operators can be quite expensive. I would suggest starting with a 2D example. If 2D works well then we can move to 3D.

**Comment by norouzzadeh** [comment]
Modeling a 3D mesh of a kidney by 1500 tetrahedrons, results in 6000 points in the 3D space.
If I'm right, I have to define a gridz for in both 2D and 3D cases?

**Comment by zongyi-li** [comment]
Yes, we will need to define a grid. The current Fourier neural operator use FFT, so we may need to convert it onto a uniform grid. For example, we can interpolate the 6000 points into, for example, 32*32*32 grid.

After all, this is a 3D problem. I will suggest first work on a 2D problem if it applies.

Usually, we need ~1000 simulations for training an operator.

**Comment by norouzzadeh** [comment]
Really thank you. I'll give it a try.

**Comment by norouzzadeh** [comment]
Just another question. In the Navier Stokes example, u(x,y) is a scalar. In my problem, u is a 3D vector of floats.
How should I define u in this case. Is there any modifications required in the FNO3D to support 3D PDE problem?

**Comment by zongyi-li** [comment]
You can put it into the channel space. For FNO3D, the input channel dimension is (10+3) and output dimension is 1. If we want to model a 3d vector field, then we can set the input dimension to be (30+3) and output dimension 3. Hope it helps!

**Comment by norouzzadeh** [comment]
Really thank you!

**Comment by gokhalen** [comment]
@zongyi-li  Does it matter how the components of the 3d vector field are put into the channel space? For instance we could put them as [u_1,v_1,w_1, u_2, v_2, w_2] or as [u_1,u_2, v_1,v_2,w_1,w_2]
