### ISSUE TITLE
Assertion exception

### ISSUE THREAD

**Issue by pacedproton** [zongyi-li/fourier_neural_operator#5]
getting this -

python3 ns_fourier_3d_rnn.py
500 0.0025 100 0.5
torch.Size([20, 256, 256, 10]) torch.Size([20, 256, 256, 10])
Traceback (most recent call last):
  File "ns_fourier_3d_rnn.py", line 197, in <module>
    assert (S == train_u.shape[-2])
AssertionError

**Comment by zongyi-li** [comment]
Hi pacedproton, 
I don't see the file ns_fourier_3d_rnn.py. 
If you mean ns_fourier_3d.py or ns_fourier_2d_rnn.py, they are for the Navier-Stokes equation, available here (also in the front page) 
https://drive.google.com/drive/folders/1UnbQh2WWc6knEHbLn-ZaXrKUZhp7pjt-
Using other datasets may lead to dimension mismatch.
Thanks!
