### ISSUE TITLE
question about the linear translation layer W

### ISSUE THREAD

**Issue by mbui0327** [zongyi-li/fourier_neural_operator#50]
Hi, I wonder why W is implemented with a `conv` here. I thought it should be just a simple linear translation.
https://github.com/zongyi-li/fourier_neural_operator/blob/fd7b0ded5370861c43cc1e014ff70e0d047d6fe9/fourier_1d.py#L87

Thanks.

**Comment by zongyi-li** [comment]
Yes, it is a linear transform in the channel dimension. A `conv` layer with filter size 1 is just a way to implement it. Equivalently we can use `nn.linear` layer, which requires permuting the dimension.
