### ISSUE TITLE
Do you have the comparison code of with FNO and without FNO for ResNet?

### ISSUE THREAD

**Issue by csdingbin** [zongyi-li/fourier_neural_operator#58]
Hi Zongyi,
Great of your work. I'm wondering can I apply your FNO to the model compression. Do you have the comparison results of with FNO and without FNO for ResNet? And do you have the comparison code of with FNO and without FNO for ResNet?

Thanks

**Comment by zongyi-li** [comment]
No we haven't studied model compression. I am not very sure what you mean about ResNet with FNO and without FNO.

**Comment by csdingbin** [comment]
I mean do you have the comparison benchmark result and code of original ResNet model and the ResNet model with FNO?

**Comment by cesare4444** [comment]
Hi Zongyi, 
Thank you for your work. I am running your fourier_2d.py: the darcy flow experiment in section5.2. The numerical result shows the L2 loss is about 0.00759 which is better than 0.0098 in your paper? I tried many times and the result is similar?

Thanks

**Comment by zongyi-li** [comment]
We don't have the ResNet model with FNO. Does it correspond to one of the model in the paper?

**Comment by csdingbin** [comment]
Maybe I misunderstand your scripts:  [https://github.com/zongyi-li/fourier_neural_operator/blob/master/scripts/fourier_on_images.py#L209](url).
I misunderstand This 'ResNet18' was built by your FNO.

**Comment by zongyi-li** [comment]
Oh sorry, this file was in construction and later obsoleted. Please ignore it. If you are interested in images problems, this paper may be interesting to you https://arxiv.org/pdf/2111.13587.pdf
