### ISSUE TITLE
Is the result of darcy flow experiment better than that in your paper?

### ISSUE THREAD

**Issue by cesare4444** [zongyi-li/fourier_neural_operator#59]
Hi Zongyi,
Thank you for your work. I am running your fourier_2d.py: the darcy flow experiment in section5.2. The numerical result shows the L2 loss is about 0.00759 which is better than 0.0098 in your paper? I tried many times and the result is similar?

Thanks

**Comment by zongyi-li** [comment]
Yes, the we have updated the activation function from ReLU to GeLU and add paddings, which improved the results.

**Comment by cesare4444** [comment]
OK，thank you very much.
