### ISSUE TITLE
RuntimeError: shape '[1000, 1024, 1]' is invalid for input of size 8192000

### ISSUE THREAD

**Issue by dbl001** [zongyi-li/fourier_neural_operator#6]
I tried running the file   fourier_1d.py:

```
$ python fourier_1d.py 
Traceback (most recent call last):
  File "fourier_1d.py", line 161, in <module>
    x_train = torch.cat([x_train.reshape(ntrain,s,1), grid.repeat(ntrain,1,1)], dim=2)
RuntimeError: shape '[1000, 1024, 1]' is invalid for input of size 8192000
```
This statement is generating the exception:
```
x_train.reshape(ntrain,s,1)

From the documentation of view() method, 'The returned tensor shares the same data and must have the same number of elements, but may have a different size.'
```
![Screen Shot 2020-11-03 at 11 20 09 AM](https://user-images.githubusercontent.com/3105499/98030913-9413fc80-1dc6-11eb-80d2-86e30fd835fa.png)

Ideas?

**Comment by iamcalvinlau** [comment]
I made the assumption that he meant to have it as 

`sub = 2**3 #subsampling rate`
`h = 2**13 // sub`
`s = h`

but I don't know if that is really the case.

**Comment by zongyi-li** [comment]
That's right. The raw data of the Burgers equation has resolution 8192. You can downsample it to the desired resolution.
