### ISSUE TITLE
maybe some thing wrong in utilities3.py ? or another bug in the code?

### ISSUE THREAD

**Issue by veyron95** [zongyi-li/fourier_neural_operator#61]
Hi, i am trying to reproduce your exepriments result.
I just change the TRAIN_PATH and TEST_PATH to '/home/data/NavierStokes_V1e-5_N1200_T20.mat' 
and change T from 40 to 10, and then run:
` python3.7 fourier_3d.py`
The result that i got as follow, maybe some thing wrong, 

Please take a look, thanks,

```
489 10.252128057181835 0.019634807519614696 0.08073463827371598 0.22321295380592346
490 8.146521881921217 0.019635397335514428 0.08073771142959595 0.2236676424741745
491 10.866600763052702 0.019629415897652505 0.08073480159044266 0.2232614892721176
492 8.50566947995685 0.019635313227772712 0.08075259721279145 0.22349709749221802
493 10.444014868000522 0.019620819902047514 0.08072293162345887 0.2237038666009903
494 12.948399811983109 0.019610148882493378 0.08068822592496872 0.2233934336900711
495 8.396875259000808 0.019591552671045065 0.08063761121034622 0.22345163762569428
496 8.427478078054264 0.019569343607872724 0.08057864302396775 0.22329660773277282
497 10.278667164035141 0.01957395510748029 0.08059006589651108 0.22355687558650972
498 8.890411228872836 0.01956247627735138 0.0805699879527092 0.22378367960453033
499 8.894694186048582 0.019547253418713807 0.0805325716137886 0.2240159559249878
Traceback (most recent call last):
  File "fourier_3d.py", line 303, in <module>
    out = y_normalizer.decode(out)
  File "/home/zongyi/fourier_neural_operator/utilities3.py", line 99, in decode
    x = (x * std) + mean
RuntimeError: The size of tensor a (10) must match the size of tensor b (64) at non-singleton dimension 3
```

**Comment by zongyi-li** [comment]
Sorry, it seems to be a shape mismatch. Could you change line 302
`out = model(x)`
to
`out = model(x).view(1, S, S, T)`

Btw, I assume you are using a very small modes/weight/training data. It seems the model is quite overfitted. In general, for a smaller time step like T=10 it may be better to use the iterative method fourier_2d_time.py.

**Comment by veyron95** [comment]
Thanks, that change works for this case.
I am using the dataset as follow:
NavierStokes_V1e-5_N1200_T20.zip

I will follow your advice to use fourier_2d_time.py.

Bug i also have a question is that why fourier_3d.py has such a high demand for CPU that scripts can barely run in a machine when it is not idle, and that each epoch takes a long time(some times takes 150s+ per epoch).
![image](https://user-images.githubusercontent.com/87417304/145546281-a8669945-7d64-4822-9159-9d6f61b18d40.png)

**Comment by YangXia9** [comment]
Hi, I'm an undergraduate trying to replicate the Darcyflow code from paper using the 'fourier_2d.py' file. 

I'm using the dataset “Darcy_421/piececonst_r421_N1024_smooth1.mat” “Darcy_421/piececonst_r421_N1024_smooth2.mat” and encountering the following error. 

How should I resolve it?
And I’m using ''2.0.1+cu118''torch version.


2376449
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[14], line 27
     24 loss = myloss(out.view(batch_size,-1), y.view(batch_size,-1))
     25 loss.backward()
---> 27 optimizer.step()
     28 scheduler.step()
     29 train_l2 += loss.item()

File ~/.conda/envs/scx7009/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:69, in LRScheduler.__init__.<locals>.with_counter.<locals>.wrapper(*args, **kwargs)
     67 instance._step_count += 1
     68 wrapped = func.__get__(instance, cls)
---> 69 return wrapped(*args, **kwargs)

File ~/.conda/envs/scx7009/lib/python3.8/site-packages/torch/optim/optimizer.py:280, in Optimizer.profile_hook_step.<locals>.wrapper(*args, **kwargs)
    276         else:
    277             raise RuntimeError(f"{func} must return None or a tuple of (new_args, new_kwargs),"
    278                                f"but got {result}.")
--> 280 out = func(*args, **kwargs)
    281 self._optimizer_step_code()
    283 # call optimizer step post hooks

File ~/.conda/envs/scx7009/lib/python3.8/site-packages/torch/optim/optimizer.py:33, in _use_grad_for_differentiable.<locals>._use_grad(self, *args, **kwargs)
     31 try:
     32     torch.set_grad_enabled(self.defaults['differentiable'])
---> 33     ret = func(self, *args, **kwargs)
     34 finally:
     35     torch.set_grad_enabled(prev_grad)

File ~/.conda/envs/scx7009/lib/python3.8/site-packages/torch/optim/adam.py:141, in Adam.step(self, closure)
    130     beta1, beta2 = group['betas']
    132     self._init_group(
    133         group,
    134         params_with_grad,
   (...)
    138         max_exp_avg_sqs,
    139         state_steps)
--> 141     adam(
    142         params_with_grad,
    143         grads,
    144         exp_avgs,
    145         exp_avg_sqs,
    146         max_exp_avg_sqs,
    147         state_steps,
    148         amsgrad=group['amsgrad'],
    149         beta1=beta1,
    150         beta2=beta2,
    151         lr=group['lr'],
    152         weight_decay=group['weight_decay'],
    153         eps=group['eps'],
    154         maximize=group['maximize'],
    155         foreach=group['foreach'],
    156         capturable=group['capturable'],
    157         differentiable=group['differentiable'],
    158         fused=group['fused'],
    159         grad_scale=getattr(self, "grad_scale", None),
    160         found_inf=getattr(self, "found_inf", None),
    161     )
    163 return loss

File ~/.conda/envs/scx7009/lib/python3.8/site-packages/torch/optim/adam.py:281, in adam(params, grads, exp_avgs, exp_avg_sqs, max_exp_avg_sqs, state_steps, foreach, capturable, differentiable, fused, grad_scale, found_inf, amsgrad, beta1, beta2, lr, weight_decay, eps, maximize)
    278 else:
    279     func = _single_tensor_adam
--> 281 func(params,
    282      grads,
    283      exp_avgs,
    284      exp_avg_sqs,
    285      max_exp_avg_sqs,
    286      state_steps,
    287      amsgrad=amsgrad,
    288      beta1=beta1,
    289      beta2=beta2,
    290      lr=lr,
    291      weight_decay=weight_decay,
    292      eps=eps,
    293      maximize=maximize,
    294      capturable=capturable,
    295      differentiable=differentiable,
    296      grad_scale=grad_scale,
    297      found_inf=found_inf)

File ~/.conda/envs/scx7009/lib/python3.8/site-packages/torch/optim/adam.py:442, in _multi_tensor_adam(params, grads, exp_avgs, exp_avg_sqs, max_exp_avg_sqs, state_steps, grad_scale, found_inf, amsgrad, beta1, beta2, lr, weight_decay, eps, maximize, capturable, differentiable)
    439 torch._foreach_add_(device_state_steps, 1)
    441 if weight_decay != 0:
--> 442     device_grads = torch._foreach_add(device_grads, device_params, alpha=weight_decay)
    444 # Decay the first and second moment running average coefficient
    445 torch._foreach_mul_(device_exp_avgs, beta1)

RuntimeError: The size of tensor a (2) must match the size of tensor b (12) at non-singleton dimension 4
