### ISSUE TITLE
About data generation 

### ISSUE THREAD

**Issue by KRISWIU** [zongyi-li/fourier_neural_operator#63]
I am looking at the file ns_2d.py  in data_generation. I thought this data generation process is about solving the data by traditional method. But I saw that it uses torch.rfft to process data through fourier space. Why do we need to process through this method? Can we just use the traditional method to solve it?

**Comment by zongyi-li** [comment]
The pseudospectral solver, which operates on the Fourier space, is one of the traditional numerical solvers. https://en.wikipedia.org/wiki/Spectral_method

**Comment by KRISWIU** [comment]
Oh, so it is using a method similar with fourier space but it is spectral method. And I also curious that in the whole process of solving (def navier_stokes_2d(w0, f, visc, T, delta_t=1e-4, record_steps=1)), the data used is the w0 which is the initial value and do we use other data in this process? Or what data is used in this spectral method?

**Comment by zongyi-li** [comment]
Yes, the numerical solvers only use the equation. In this case, it only requires the initial condition w0. It doesn't need additional data.

**Comment by KRISWIU** [comment]
Oh, thanks!
