### ISSUE TITLE
Dependence of training on initial conditions

### ISSUE THREAD

**Issue by alexguev** [zongyi-li/fourier_neural_operator#64]
Hi,

Thanks for sharing your work, which should be very helpful for many fields. I was wondering whether the model had to be re-trained whenever the initial conditions are changed? Or training the model with respect to the set of PDEs is sufficient, irrespective of the initial conditions? If it is the latter, has your model been tested when the initial conditions change drastically from the training to the prediction (for a given set of PDEs)?

**Comment by zongyi-li** [comment]
Thank you for the kind words. We are learning a model working for a distribution of the initial conditions. Take the 2D Darcy elliptic equation as an example, we assume both the training and test data have initial conditions sampled from a Gaussian random field, which covers a diverse group of initial conditions. However, it will still be very challenging if we want to test the initial conditions with very different contrast.

**Comment by alexguev** [comment]
Thanks for your prompt reply. 

1) So I understand the model should be predictive when tested on a set of initial conditions that is close enough to the sets it was trained on; this commonality can for instance be achieved when generated from a similar distribution (e.g. a normal distribution with different variances) - right? This should be interesting to study further, I might look into it.

In that regard, could you please briefly explain what is in the variance of your normal distributions in your May 2021 paper (A.3.2 e.g.)? Or point toward another paper where that is discussed?

2) That said, to check my understanding, even if I had to train my model to learn a new set of initial conditions every time, it might still be advantageous to do so for the following reason. Say I know that my simulation will demand a very fine mesh to obtain mesh-converged results. Then I could train my model on a fairly coarse mesh (I suppose there is a limit to "how coarse"), and predict the results of my simulation for a finer mesh - for instance to run a mesh convergence study but without having to run the simulations for every successive finer meshes? I hope I'm clear enough ^^

**Comment by zongyi-li** [comment]
Sorry for the long delay! 

We sample from a gaussian random field. In practice, it is done by sampling random Fourier coefficient, and scale with respect to their wavenumber, so we get smooth random initial condition. The implementation is at https://github.com/zongyi-li/fourier_neural_operator/blob/master/data_generation/navier_stokes/random_fields.py.

For the second part, if I understand correctly, it means we can train a model that input the coarse solution and predict the finer solution. Yes, that sounds very interesting. We just need to prepare such as dataset that consists of coarse and fine simulation.
