### ISSUE TITLE
How to determine the padding size?

### ISSUE THREAD

**Issue by tony-hd** [zongyi-li/fourier_neural_operator#65]
Hi Zongyi,

Thank you for sharing your great work! I want to know how to determine the padding size before performing FFT. Below are codes from your python files. @zongyi-li 

in fourier_2d.py
self.padding = 9 # pad the domain if input is non-periodic

in fourier_3d.py
self.padding = 6 # pad the domain if input is non-periodic

Thanks !
Tony

**Comment by zongyi-li** [comment]
How Tony,

If the problem is periodic, usually we don't need to pad. For non-periodic domain, larger padding is usually slighly better. As a rule of thumb, we just pad ~10.

Thanks,
Zongyi
