### ISSUE TITLE
Question about Data Generation

### ISSUE THREAD

**Issue by dashu233** [zongyi-li/fourier_neural_operator#66]
Hi, zongyi, thank you for your excellent work! I'm trying to examine FNO in a more complicated setting so I have to regenerate some data for my experiments. I use data_generation/navier_stokes/ns_2d.py but I notice the output solution is in the shape of [20, 64, 64, 200], where the last dimension is supposed to be 30 for the T=30 setting. Could you please tell me which parameter should I change?

**Comment by zongyi-li** [comment]
You may want to change `record_steps=30` which sets how many time steps to record.
