### ISSUE TITLE
Fno for x and time

### ISSUE THREAD

**Issue by soumyadiptapete** [zongyi-li/fourier_neural_operator#68]
Hi,
Can I use the fourier2d.py for data containing 1 spatial dimension and 1 time dimension?

Thanks
Soumyadipta

**Comment by zongyi-li** [comment]
Hi Soumyadipta, sorry for the delayed response. Yes, you can apply fourier2d.py for data containing 1 spatial dimension and 1 time dimension. It is the way to use it.

**Comment by Tariq97** [comment]
Hi, First, this is a very interesting technique. 
I have a question, if I were to implement time dependent 1D Berger equation, say I give solutions of first 10 steps and expect the next 20 steps, do you think fourier2d_time would work for that? This would be a 1dimensional problem..
Please let me know.

Thanks,
Tariq

**Comment by zongyi-li** [comment]
Dear Tariq,

Yes, you can use the training/inference code like fourier2d_time, just change the network model from FNO2d to FNO1d.

Thanks,
Zongyi
