### ISSUE TITLE
Can You Open 'burgers_v1000_t200_r1024_N2048.mat'?

### ISSUE THREAD

**Issue by dbl001** [zongyi-li/fourier_neural_operator#7]
Can you open 'burgers_v1000_t200_r1024_N2048.mat'?  I am getting exceptions in Python, Matlab and Mathematica.

![Screen Shot 2020-11-02 at 8 06 17 AM](https://user-images.githubusercontent.com/3105499/98141073-0b0acd00-1e7b-11eb-80f5-193da5a4d95f.png)

![Screen Shot 2020-11-04 at 8 52 37 AM](https://user-images.githubusercontent.com/3105499/98141118-1d850680-1e7b-11eb-8d9f-4d46901e7c08.png)

**Comment by zongyi-li** [comment]
Oh sorry, I download the data file and it seems corrupted. 
Just uploaded another one. It should work now https://drive.google.com/drive/folders/1UnbQh2WWc6knEHbLn-ZaXrKUZhp7pjt-
Thanks!

**Comment by dbl001** [comment]
Thanks!

Which python program uses 'burgers_v1000_t200_r1024_N2048.mat’?

There’s a comment around TEST_PATH in ‘scripts/spectral_study1d.py’, 
however, the file doesn’t have a ‘pred’ attribute.

**Comment by zongyi-li** [comment]
Please use -fourier_1d.py- for the Burgers equation. 
The file -scripts/spectral_study1d.py- is to evaluate the spectral decay. I guess you won't need it. 
Thanks!

**Comment by dbl001** [comment]
Here do I get these data files?

fourier_2d.py:TRAIN_PATH = 'data/piececonst_r421_N1024_smooth1.mat'
fourier_2d.py:TEST_PATH = 'data/piececonst_r421_N1024_smooth2.mat'
lowrank_2d.py:TRAIN_PATH = 'data/piececonst_r421_N1024_smooth1.mat'
lowrank_2d.py:TEST_PATH = 'data/piececonst_r421_N1024_smooth2.mat'

**Comment by zongyi-li** [comment]
These are the Darcy Flow equation given in the dataset https://drive.google.com/drive/folders/1UnbQh2WWc6knEHbLn-ZaXrKUZhp7pjt- https://drive.google.com/drive/folders/1UnbQh2WWc6knEHbLn-ZaXrKUZhp7pjt-
Thanks!

**Comment by dbl001** [comment]
Can you open these files:

-rw-r--r-- 1 ubuntu ubuntu   54411264 Feb 14  2020 piececonst_r421_N1024_smooth1.mat
-rw-r--r-- 1 ubuntu ubuntu 1692748750 Feb 14  2020 piececonst_r421_N1024_smooth2.mat

**Comment by zongyi-li** [comment]
Yes I just downloaded them and I can open them with no problem. It seems you didn't download the full file. Each of them should be approximately 1.6 GB.

**Comment by dbl001** [comment]
Agreed.
