### ISSUE TITLE
Very different performance on Burgers1D across different versions of code

### ISSUE THREAD

**Issue by zijieli-Jlee** [zongyi-li/fourier_neural_operator#71]
First of all, thanks for open-sourcing this great project!

I noticed that when I tested fourier_1d.py on the "burgers_R10.mat", I got different results (with a relatively large gap) using different versions of code with different Pytorch versions. Below are the results I got.

* Using up-to-date code, without changing a single line of the code, if I run the ```fourier_1d.py``` in the root directory under PyTorch 1.8.1+CUDA10.2, the test_l2 is ```~0.0006``` for different resolutions.
* If I change the optimizer from your customized version of Adam to "torch.optim.Adam", this yields a test_l2 of ```~0.0010```, still very good.
* As suggested in this issue #49 , I use torch 1.6+CUDA10.2 to run the scripts under ```FNO-torch1.6```, this results in a test_l2 around ```0.0027```.

May I ask what could be the possible reason about this gap between different versions of code? Any suggestions will be appreciated.

**Comment by zongyi-li** [comment]
Yes, the error` ~0.0006` is expected. It's mainly coming from using `gelu` instead of `relu`. Thanks

**Comment by zijieli-Jlee** [comment]
I see, thanks for the reply!
