### ISSUE TITLE
Data Generation

### ISSUE THREAD

**Issue by BraveDrXuTF** [zongyi-li/fourier_neural_operator#73]
Thanks for your great work!
I'm trying to regenerate data using [gen_burgers1.m](https://github.com/zongyi-li/fourier_neural_operator/blob/master/data_generation/burgers/gen_burgers1.m), and I find I have no **chebfun**, I have no idea 
what it is. Could you tell me what it is?
Thank you very much!

**Comment by BraveDrXuTF** [comment]
And spinop in [burgers1.m](https://github.com/zongyi-li/fourier_neural_operator/blob/master/data_generation/burgers/burgers1.m), thx!

**Comment by lixuekai2001** [comment]
Got the same problem and fix it by downloading chebfun and add into Matlab.

**Comment by zongyi-li** [comment]
Yes, you may need to download the chebfun package in Matlab.

**Comment by BraveDrXuTF** [comment]
Thank you, I got it.
