### ISSUE TITLE
What is LP loss?

### ISSUE THREAD

**Issue by Sakurapola** [zongyi-li/fourier_neural_operator#77]
Hi, this is a very exciting work! But I'm a little bit confused about LP loss, could you please explain more about the choose of loss function?

**Comment by zongyi-li** [comment]
We use the relative Lp loss. 
`L = ||target - pred||_p / ||target||_p.`
The L2 norm is similar to the MSE loss. The normalization (denominator) is quite important.

**Comment by br92sil** [comment]
Hi Zongyi!

I would also like to understand what motivates using this Lp Loss. Would you be able to recommend any references? 

**Why is the denominator quite important?** 

Thanks.
