### ISSUE TITLE
Location of: data/ns_data_V100_N1000_T50_1.mat

### ISSUE THREAD

**Issue by dbl001** [zongyi-li/fourier_neural_operator#80]
Where do I find these files?
```
fourier_3d.py:TRAIN_PATH = 'data/ns_data_V100_N1000_T50_1.mat'
fourier_3d.py:TEST_PATH = 'data/ns_data_V100_N1000_T50_2.mat'
```
They do not appear in: NavierStokes_V1e-3_N5000_T50.zip

https://drive.google.com/file/d/1r3idxpsHa21ijhlu3QQ1hVuXcqnBTO7d/view?usp=sharing

**Comment by zongyi-li** [comment]
Sorry for the confusion. We combine these data and upload them as one file.` ns_data_V100_N1000_T50_1.mat` and `ns_data_V100_N1000_T50_2.mat` are the [0:1000] and [1000:2000] rows of the `NavierStokes_V1e-3_N5000_T50.zip` dataset.
