### ISSUE TITLE
Data generation for Darcy_2d

### ISSUE THREAD

**Issue by ach14012022** [zongyi-li/fourier_neural_operator#81]
Hi All. 
The computational domain of my case is set to be [0, 1]@[0, 1]. A 30@30 uniform mesh is selected for the fine grid system, and subsequently, there are 31@31 nodes. A typical permeability field (input)/its corresponding pressure distribution (output) is given below. By the way, I have access to the values of input/output in terms of 900@1 tensor. I was wondering how I should use my data for FNO (e.g. what dimension). 
![perm](https://user-images.githubusercontent.com/109968311/194266533-9d20fbbe-5920-4380-9d1c-b680a5c5d14f.JPG)
![pressure](https://user-images.githubusercontent.com/109968311/194266613-204f7533-a8da-40d2-bba9-a52c717ae21b.JPG)
Tnx so much.

**Comment by zongyi-li** [comment]
Hi Abouzar, 
Usually we shape the input and output as (N,X,Y,C). In your case it will be (N, 31, 31, 1). I notice 31 might be a bit too coarse.

Do you want to train a FNO model with your dataset, or use an existing model to do the inference for your case? 

Besides, it seems the permeability field is active on the bottom left corner, but the pressure field is constant on the y-axis. Should the pressure field be also concentrated on the bottom left corner too?

**Comment by ach14012022** [comment]
Dear Zongyi,
Tnx so much.
About the dimension of my problem, it is in the direction of another project. So, I cannot change it.
Yes, I want to work on my dataset.
The permeability field affects the pressure distribution. In the figures above, it is not clear enough sadly.
