### ISSUE TITLE
Visualization for fourier_2d

### ISSUE THREAD

**Issue by ach14012022** [zongyi-li/fourier_neural_operator#82]
Hi All, 
There is no section for the visualization of the results in the link below:
[](url)https://github.com/zongyi-li/fourier_neural_operator/blob/master/fourier_2d.py
Plus, what are r, h, and s in the configs section?
Any idea plz?
Tnx so much.

**Comment by zongyi-li** [comment]
For visualization, you can use the default imshow function https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html

`r` is the sample rate; `h` and `s` are the grid size. In this case, the raw data has the size (421, 421), and the downsample rate `r=5`, so the resulting grid size `h=s=85`.

**Comment by ach14012022** [comment]
Tnx for your comment.
First: are we allowed to test different values for r, h, and s?
Second: it seems that by defining r, h, and s, FNO works based on train data with new dimensions i.e., (85, 85), not the initial state i.e., (421, 421). On the other hand, we are going to find the solution (output) over the initial state. So, for visualization how we can convert (85, 85) to (421, 421)?

**Comment by zongyi-li** [comment]
Yes, we can test on different values of r and h=s.
For visualization, we can directly apply the imshow() function on (85, 85) and/or (421, 421) outputs.

**Comment by ach14012022** [comment]
Sorry, a bit confusing. When we are training a model based on the data size of (85, 85) for the input/output, how it is possible to convert the size to (421, 421).
What is the benefit of defining r, h, and s, and subsequently decreasing the dimension?
Are we allowed to train based on raw data (421, 421)?

**Comment by zongyi-li** [comment]
We can train a model based on the data size of (85, 85) for the input/output, save the model, and evaluate it on new input of size (421, 421). In this case we will get output of size (421, 421). In this sense the model is can be generalized to problem of different resolution, but we are not doing super-resolution (input 85 and output 421).

**Comment by ach14012022** [comment]
Do you mean we can use r, h, and s for the train data while keeping the initial data size (421, 421) for the test data?

**Comment by zongyi-li** [comment]
Yes it is correct.

**Comment by mclovivin** [comment]
> For visualization, you can use the default imshow function https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html
> Hi @zongyi-li 
I wanted to display the inference results of fourier_3d.py, and referring to the discussion here, I displayed the correct data and inference results at t=0, i.e. y and pred, for now.
However, it seems that the y and pred results are already different at the initial condition of t=0.
What went wrong?

code
```
with torch.no_grad():
    for x, y in test_loader:
        test_l2 = 0
        x, y = x.cuda(), y.cuda()

        out = model(x).view(1, S, S, T)
        out = y_normalizer.decode(out)
        pred[index] = out

        test_l2 += myloss(out.view(1, -1), y.view(1, -1)).item()
        print(index, test_l2)
        index = index + 1
        print("pred", pred.shape)
        print("y", y.shape)

plt.imshow(y.cpu().numpy()[0,:,:,0])
plt.show()
plt.imshow(pred.cpu().numpy()[0,:,:,0])
plt.show()
```
Grand Truth and Prediction, respectively, are as follows.


Grand Truth

![image](https://user-images.githubusercontent.com/120172950/206670569-252bb44a-4f75-42e1-b7a9-7adf6831ee92.png)

Prediction
![image](https://user-images.githubusercontent.com/120172950/206670846-e97aeb44-0e83-4e03-ac25-5960fd892489.png)

**Comment by zongyi-li** [comment]
Sorry this piece of code may be outdated. It did use the auto-regressive structure as in training and validation.
Could you use/copy lines 236-261 to do visualization?

**Comment by mclovivin** [comment]
OK
This is the result.

Grand Truth
![image](https://user-images.githubusercontent.com/120172950/206793469-46b48679-3b1a-4914-adbc-379c946fbab0.png)

Prediction
![image](https://user-images.githubusercontent.com/120172950/206793506-7b3dc0c3-ed87-4a93-8599-e58076d06488.png)

Probably correct.

**Comment by zongyi-li** [comment]
what is the test_l2 error in this case? Usually error <0.05 means a very close prediction.
You may also want to set the same `vmin` and `vmax` in `plt.imshow()` for truth and prediction, so they have the same color axis.
Another potential issue is that the resolution is a bit too coarse (16x16), you may need a higher resolution to represent the dynamics.

**Comment by mclovivin** [comment]
Okay, how can I increase the resolution?
I might change the data set and modify this section
S and train_u.shape[-2] to match, but I get an error.

Error location
```train_a = train_a.reshape(ntrain,S,S,1,T_in).repeat([1,1,T,1])```

Error content
```RuntimeError: shape '[1000, 64, 64, 1, 10]' is invalid for input of size 819200```

Dataset
ns_data_V1e-4_N20_T50_R256test

I am sorry to bother you, but could you please let me know?
