### ISSUE TITLE
Some questions when I want to reproduce experiment

### ISSUE THREAD

**Issue by 5huanghuai** [zongyi-li/fourier_neural_operator#84]
Recently, when I have been learning the Fourier Neural Operator. But I have faced some questions. I would be grateful if someone could help me to confirm these questions.
Firstly, I didn’t get not ideal production when I used origin setting model (NavierStokes_V1e-5_N1200_T20.mat as dataset) to infer. I don’t know whether the variants "model1, modes2, modes3" in SpectralConv3d is so large that the output of inference lost most of the high frequency data? I think the reason is that the variants "model1,modes2,modes3" in SpectralConv3d is too big, so the filters delete too much high frequency. I don't know if it is right. Here are my model prediction.
![output](https://fastly.jsdelivr.net/gh/5huanghuai/Image@main/image/1667789691637out.png)
![predict](https://fastly.jsdelivr.net/gh/5huanghuai/Image@main/image/1667789699890label.png)

**Comment by zongyi-li** [comment]
Please feel free to try with more Fourier modes. It's possible that the V1e-5 dataset is too chaotic and the amount of data is not sufficient. I would suggest playing with the lower Reynolds number setting.
