### ISSUE TITLE
Super_resolution

### ISSUE THREAD

**Issue by hengxing-2020** [zongyi-li/fourier_neural_operator#85]
Hi,

Thanks for sharing your work, which should be very helpful for many fields. I'm doing some research on super resolution. I would appreciate it if you could answer my questions. Firstly, can you tell me the purpose and difference of the files fourier_2d, fourier-2d_time,fourier_3d,fourier_3d_time,super_resolution and eval? Secondly, which is the code for the pre-trained model of super_resolution? Thirdly, what is the relevant parameter setting for pre-training? How are the parameters for generating training data and test data set?

**Comment by zongyi-li** [comment]
fourier_2d: 2d -> 2d mapping, e.g. Darcy Flow
fourier-2d_time: 2d time sequence, e.g. Navier-Stokes
fourier_3d: 3d -> 3d mapping, e.g. Navier-Stokes, but take time as 3rd spatial dimension.
super_resolution and eval might be obsolete (based on the pytorch 1.6 version).
You can train a model with fourier_3d with low resolution dataset (NavierStokes_V1e-4_N20_T50_R256_test\), and then evaluate it on higher resolution data (ns_data_V1e-4_N20_T50_R256test.mat).
