### ISSUE TITLE
RuntimeError: The size of tensor a (256) must match the size of tensor b (64) at non-singleton dimension 2

### ISSUE THREAD

**Issue by Sh1gechan** [zongyi-li/fourier_neural_operator#87]
@zongyi-li 
Thank you for sharing the implementation code of this great experiment.
After running fourier_3d.py using the dataset provided by [drive](https://drive.google.com/drive/folders/1UnbQh2WWc6knEHbLn-ZaXrKUZhp7pjt-), we ran into the following problem with the Navier-Stokes equation dataset.

I tried running the file fourier_3d.py with NavierStokes_V1e-5_N1200_T20\NavierStokes_V1e-5_N1200_T20.mat train_data:
```python .\fourier_3d.py  
500 0.001 100 0.5
torch.Size([1000, 64, 64, 10])
torch.Size([20, 256, 256, 40])
Traceback (most recent call last):
  File "fourier_3d.py", line 215, in <module>
    assert (T == train_u.shape[-1])
AssertionError
```
Next, using NavierStokes_V1e-5_N1200_T20\NavierStokes_V1e-5_N1200_T20.mat and NavierStokes_V1e-3_N5000_T50\ns_V1e-3_N5000_T50.mat train_data I ran fourier_3d.py and got the following error:

```$ python .\fourier_3d.py     
500 0.001 100 0.5
torch.Size([1000, 64, 64, 40])
torch.Size([20, 256, 256, 40])
Traceback (most recent call last):
  File "fourier_3d.py", line 220, in <module>
    test_a = a_normalizer.encode(test_a)
  File "utilities3.py", line 83, in encode
    x = (x - self.mean) / (self.std + self.eps)
RuntimeError: The size of tensor a (256) must match the size of tensor b (64) at non-singleton dimension 2
```
For all test_paths, NavierStokes_V1e-4_N20_T50_R256_test\ns_data_V1e-4_N20_T50_R256test.mat
was used to run the simulation.

What should I fix?

**Comment by zongyi-li** [comment]
NavierStokes_V1e-5_N1200_T20.mat has resolution 64x64.
ns_data_V1e-4_N20_T50_R256test.mat has resoluton 256x256. 
You can set sub = 4 when reading test data (line 210-211), so the shape matches.
Alternatively you can use the same path (NavierStokes_V1e-5_N1200_T20.mat) and pick the last 200 instances for validation/testing.

**Comment by Sh1gechan** [comment]
@zongyi-li Thank you for your reply.
Resolved successfully.
