### ISSUE TITLE
RuntimeError: The size of tensor a (128) must match the size of tensor b (13312) at non-singleton dimension 1

### ISSUE THREAD

**Issue by mclovivin** [zongyi-li/fourier_neural_operator#89]
I tried to use the published Burgers equation data set but could not get it to run.
The [datasets](https://drive.google.com/drive/folders/1UnbQh2WWc6knEHbLn-ZaXrKUZhp7pjt-?usp=sharing) are Burgers_v100 and Burgers_v1000-006.

The error message is as follows
RuntimeError: The size of tensor a (128) must match the size of tensor b (13312) at non-singleton dimension 1

The error occurs at line 191 of fourier_1d.py
```mse = F.mse_loss(out.view(batch_size, -1), y.view(batch_size, -1), reduction='mean')```

This is probably an error that comes from the fact that out and y have different shapes, but is there something I need to change each time I change the data set?
And in this case, which part must be corrected?

Data loader settings
```
x_data = dataloader.read_field('input')[:,::sub].
y_data = dataloader.read_field('output')[:,::sub].
```

**Comment by zongyi-li** [comment]
Yes, the `Burgers_v100` and `Burgers_v1000` datasets may have a different shape compared to `Burgers_R10`.
Could you print the shape of `x_data` and `y_data`?

**Comment by mclovivin** [comment]
OK
```
x_data torch.Size([2048, 128])
y_data torch.Size([2048, 13, 1024])
```

**Comment by zongyi-li** [comment]
I see, the raw size of y_data is ([2048, 101, 1024]) where 101 is time(t) and 1024 is space(x). If we just want to learn the mapping from t=0 (first frame) to t=1 (last frame), we can read the data with
`y_data = dataloader.read_field('output')[:,-1,::sub].`
and you can optionally use a smaller sub to get finer resolutions.

**Comment by mclovivin** [comment]
I tried changing the shape of y_data, but the shape still does not seem to match.
I got the following error
```
File "fourier_1d.py", line 193, in <module
mse = F.mse_loss(out.view(batch_size, -1, 1), y.view(batch_size, -1, 1024), reduction='mean')
RuntimeError: shape '[20, -1, 1024]' is invalid for input of size 2560
```

I thought I needed to change the out shape, so I printed the shape and got the following.
```
out torch.Size([20, 128, 1])
y torch.Size([20, 128])
```
I think this shape is correct. What could be the cause?

**Comment by mclovivin** [comment]
It worked fine. Thank you very much.
