### ISSUE TITLE
Parameter not understood in nn.Linear(?, self.width)

### ISSUE THREAD

**Issue by szat** [zongyi-li/fourier_neural_operator#9]
Dear fellow scholars,
Great paper, but I struggle to understand the first argument in this call
1d:
self.fc0 = nn.Linear(2, self.width) [line 59]
2d:
self.fc0 = nn.Linear(3, self.width) [line 68]
2d_rnn:
self.fc0 = nn.Linear(12, self.width) [line 66]
3d:
self.fc0 = nn.Linear(13, self.width) [line 76]

Could you let me know, why 2, 3, 12, and 13?
Thanks for the amazing work :)

**Comment by zongyi-li** [comment]
For 1d, the input v_0(x) = (x, a(x)), the location (1d) and the input function.
For 2d, the input v_0(x) = (x, y, a(x,y)), the location (2d) and the input function.

For 2d_rnn, the input v_0(x, t) = (x, y, u(x,y,t-10), u(x,y,t-9), ..., u(x,y,t-1)), the location (2d) and the input function of the first 10 time-steps.
For 3d, the input v_0(x, t) = (x, y, t, u(x,y,1), u(x,y,2), ..., u(x,y,10)), the location (3d) and the input function of the first 10 time-steps.

Hope it helps!

**Comment by florianwechsung** [comment]
Hi @zongyi-li ,

this definition of the input first layer seems to be different to what you claim to do in the paper, doesn't it? There you write (~line 4 of Section 3), that `v_0(x) = P(a(x))`. If I understand your comment above correctly, that should actually be
`v_0(x) = P(x, a(x))` for 1D example
`v_0(x) = P(x, y, a(x, y))` for the 2D example
etc.. Is that correct?

**Comment by zongyi-li** [comment]
Hi @florianwechsung ,
Thanks for the catch! We will update it in the paper. I guess we didn't have the location in the earlier version of the implementation, but later we found it helpful to capture location-wise and non-periodic information.
`v_0(x) = P(x, a(x))` is correct. It's also included in the previous paper [GNO](https://arxiv.org/pdf/2003.03485.pdf), Eq 7.
