### ISSUE TITLE
Understanding time grid in `fourier_3d.py`

### ISSUE THREAD

**Issue by kristiantorres** [zongyi-li/fourier_neural_operator#91]
Hi Zongyi! Congrats on your fruitful research. 

This is probably a very stupid question but, can you please explain me why are you getting rid of the first sample (i.e., 0.) in the time grid (this is for `fourier_3d.py`).

`gridt = torch.tensor(np.linspace(0, 1, T+1)[1:], dtype=torch.float)`  

Why can't you just simply do
`gridt = torch.tensor(np.linspace(0, 1, T), dtype=torch.float)`?

Thanks!

**Comment by zongyi-li** [comment]
Hi Kristian, the output data does not include the t=0 frame. It starts from the second frame of the trajectory. But it probably doesn't matter much. Both line should work.
