### ISSUE TITLE
Code for PINO

### ISSUE THREAD

**Issue by nevoliu** [zongyi-li/fourier_neural_operator#92]
Hi Zongyi,
Great of your work. I am very interested in the application of FNO in CFD, I would like to know where I can find the relevant code of PINO.Will this code be open source soon?

Thanks

**Comment by zongyi-li** [comment]
Hi Nevo,
The PINO code is available at https://github.com/devzhk/PINO

Thanks,
Zongyi

**Comment by nevoliu** [comment]
Thank you very much for your contribution!
