### ISSUE TITLE
Some questions about the time dimension of FNO3d

### ISSUE THREAD

**Issue by douhongkun** [zongyi-li/fourier_neural_operator#94]
Hello, first of all, congratulations on your very enlightening work. But I have some questions about FNO3d.  You put the time dimension of input at the end and added an additional channel to repeat T times. Is this to achieve super-resolution in the time dimension? What's more, the input dimension of self.p is fixed at 13, which makes the model only accept input of 10 timescales. Unlike space dimension, it can accept the input with any resolution, which makes the model not flexible in the number of input time steps. What do you think could be done to help ease this problem? Thank you.
![image](https://user-images.githubusercontent.com/77845036/209442664-6205819e-8840-45c3-a36a-a1d886f2c893.png)
![image](https://user-images.githubusercontent.com/77845036/209442671-85b87680-d60a-4a93-819f-173f70e07bac.png)

**Comment by zongyi-li** [comment]
Hi Hongkun,
Thank you for your question. This current implementation fixes the number of input frames as 10. As a quick fix for the super-resolution task, you can try downsampling the input to 10 frames. The output can have an arbitrary resolution. 
Alternatively, you can maintain the input time as the time dimension. In this case, you can set `out=T_out` in `irfft` to adjust the shape. You may also need to add an `F.interpolate` layer for `self.w`.

Thanks,
Zongyi

**Comment by douhongkun** [comment]
Thanks, this is very helpful to me.
